version: '3'

services:
  ai-scientist:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount input/output directories to persist data with proper permissions
      - ./experiments:/workspace/ai_scientist/experiments:rw,z
      - ./ai_scientist:/workspace/ai_scientist/ai_scientist:rw,z
      - ./input:/workspace/ai_scientist/input:rw,z
    environment:
      # API Keys (fill these in or use .env file)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - S2_API_KEY=${S2_API_KEY}
      # AWS credentials for Claude models (optional)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION_NAME=${AWS_REGION_NAME}
    
    # Change entrypoint to keep container running indefinitely
    entrypoint: ["bash", "-c", "source activate ai_scientist && tail -f /dev/null"]
    # Add container name for easier reference
    container_name: ai_scientist_service
    
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    
    # Keep container running unless explicitly stopped
    restart: unless-stopped 